name: CI/CD Pipeline for Databricks ETL (Deploy Only)

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    name: Test and Deploy ETL Script
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up a Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install all the necessary Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4: Run Unit Tests (Quality Gate)
      - name: Run Unit Tests with Pytest
        run: pytest tests/

      # Step 5: Deploy the entire directory ---
      - name: Deploy src directory to Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "Deploying the entire src directory to /Shared/ETL/ on Databricks..."
          # Use import_dir to upload the whole folder.
          # The destination folder /Shared/ETL will be created if it doesn't exist.
          databricks workspace import_dir \
            src \
            /Shared/ETL
          echo "Deployment successful."